### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by Suripopik** [MarioniLab/Spermatogenesis2018#19]
Hi, I'm trying to reproduce your analysis, particularly the Velocyto analysis. But unfortunately I don't understand where to get the spliced and unspliced RNA data in .loom format. Could you please tell me if there is any way to get them?
![RNAPNG](https://github.com/MarioniLab/Spermatogenesis2018/assets/144167350/a9f915c7-39f8-43f6-b415-7e87c2537350)

**Comment by nilseling** [comment]
Hi @Suripopik 

Since we never used this in the paper I wouldn't know where this data is and can't remember how I generated this file. By now there are a bunch of better approaches to estimate RNA velocity from scRNAseq data.

**Comment by nilseling** [comment]
Closing now due to inactivity
